#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
HOME = "/opt/PNC/"
sys.path.append(HOME)
del sys

from cluster import service

def main():
    print 'initialize cluster service...'
    server = service.Cluster(False)
    server.self_register()
    print 'start cluster service...'
    server.start()
    print 'start cluster done'
    raw_input()
    stop_service()

def stop_service():
    import xmlrpclib
    server = xmlrpclib.ServerProxy('http://localhost:18002')
    try: server.stop()
    except: pass

if __name__ == '__main__':
   main()
